fos_rest:
  view:
    view_response_listener:  true
    formats:
      json: true
  exception:
    exception_controller: 'fos_rest.exception.controller:showAction'
    codes:
      Doctrine\ORM\EntityNotFoundException: 404
  format_listener:
    rules:
    - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [json] }
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  body_listener:
    enabled: true

